# Generated by Django 3.2.9 on 2022-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_timeslot_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='timeslot',
            field=models.CharField(choices=[('0', '00:00 – 00:00'), ('1', '10:00 – 10:30'), ('2', '11:00 – 11:30'), ('3', '12:00 – 12:30'), ('4', '13:00 – 13:30'), ('5', '14:00 – 14:30'), ('6', '15:00 – 15:30'), ('7', '16:00 – 16:30'), ('8', '17:00 – 17:30')], default='0', max_length=20),
        ),
    ]
