# Generated by Django 3.2.9 on 2022-07-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeappointment',
            name='time',
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timeslot'),
        ),
    ]
